### ISSUE TITLE
Incompatible package warning

### ISSUE THREAD

**Issue by LeEnno** [braver/SublimeSass#100]
Since 3.0.0 I'm receiving this warning when starting Sublime:

> The following incompatible
package was found installed:
>
> Sass
>
> This is usually due to syncing
packages across different
machines in a way that does not
check package metadata for
compatibility.

<img width="372" alt="Bildschirmfoto 2022-11-14 um 08 54 37" src="https://user-images.githubusercontent.com/2038814/201846763-3a1fd578-952f-4f61-95fe-5abb58b4bef6.png">

I don't actually do any syncing via Dropbox or anything else.  
Is there anything I can do to get rid of this message?

**Comment by braver** [comment]
Uninstall the package, ensure nothing like it remains in the Packages directory, then re-install?

**Comment by LeEnno** [comment]
That did the trick. Thank you!

**Comment by braver** [comment]
Nice :) Weird though, but if that solves it 🤷🏻

**Comment by LeEnno** [comment]
Just another note on this one: I downgraded to Sublime build 4126 for [other reasons](https://github.com/sublimehq/sublime_text/issues/5682). After updating to build 4143 again I got the SASS 3.0.0 post install message again and the incompatibility alert again.

**Comment by braver** [comment]
Oh, I think I get it. Newer builds for ST will get a newer version of Sass as well. Those older tags are set as being incompatible with certain version of ST to make that transition happen. It should automatically resolve itself 🤞🏻
