### ISSUE TITLE
Weird syntax highlighting for placeholder selectors

### ISSUE THREAD

**Issue by brybrant** [braver/SublimeSass#101]
![example](https://user-images.githubusercontent.com/31571216/202800386-570b5563-9207-489d-8c7b-a2ac5dc41b78.png)

the placeholder selector name used to appear all same colour (green) like other selectors before updating sublime text to new build (4143)

**Comment by brybrant** [comment]
this issue affects SCSS syntax but not Sass syntax.

my current workaround is capitalizing the first letter of every placeholder class i create.

![image](https://user-images.githubusercontent.com/31571216/210069515-97e7910d-60ed-4a2f-87e8-e356d21124b1.png)

please fix soon

**Comment by braver** [comment]
Sorry, this dropped off my radar for a while, but it's a seemingly easy fix.

**Comment by braver** [comment]
You'll have to wait a while until the simplify branch lands though.
