### ISSUE TITLE
Incorrect highlighting of some Sass’ @-directives

### ISSUE THREAD

**Issue by indrekpaas** [braver/SublimeSass#11]
Code examples are based on [Sass directives](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#directives) documentation.

<details>
  <summary>Reference code for testing</summary>

```scss
// @import
@import "foo.scss";

// @media
@media (orientation: landscape) {}

// @extend
.seriousError {
  @extend .error;
}

// @at-root
.parent {
  @at-root .child {}
}

// @debug
@debug 10em + 12em;

// @warn
@mixin adjust-location($x, $y) {
  @if unitless($x) {
    @warn "Assuming #{$x} to be in pixels";
  }
}

// @error
@mixin adjust-location($x, $y) {
  @if unitless($x) {
    @error "$x may not be unitless, was #{$x}.";
  }
}

// @if
p {
  @if 1 + 1 == 2 {}
}

// @for
@for $i from 1 through 3 {}

// @each (list items)
@each $animal in puma, sea-slug, egret, salamander {}

// @while
@while 6 > 0 {}

// @mixin
@mixin large-text {}

// @include
.page-title {
  @include large-text;
}

// @function and @return
@function grid-width($n) {
  @return $n * 40px + ($n - 1) * 10px;
}
```
</details>

Above code reference includes all tested code, below screenshots include only problematic code.

![image](https://user-images.githubusercontent.com/6239035/46595769-c25e7980-cb25-11e8-8512-53a9c65577f9.png)
![image](https://user-images.githubusercontent.com/6239035/46595802-ea4ddd00-cb25-11e8-97f7-d68c2d5814d2.png)
![image](https://user-images.githubusercontent.com/6239035/46595847-0baec900-cb26-11e8-8a96-322b8ac9adfa.png)
![image](https://user-images.githubusercontent.com/6239035/46595890-2bde8800-cb26-11e8-90cc-343ae73c4a9f.png)
![image](https://user-images.githubusercontent.com/6239035/46595904-3ef15800-cb26-11e8-9f71-3ae04eb09c06.png)
![image](https://user-images.githubusercontent.com/6239035/46595956-7b24b880-cb26-11e8-8579-59e48cc27ca9.png)
![image](https://user-images.githubusercontent.com/6239035/46595975-91327900-cb26-11e8-9728-1ebab32fd898.png)
![image](https://user-images.githubusercontent.com/6239035/46596014-b0310b00-cb26-11e8-96f4-415a4b5c33f0.png)

**Comment by braver** [comment]
I think it's mostly ok now. I need to spend more time on maps, there are a bunch of different issues and the approach is too simplistic right now. Also, dashes in unquoted strings are a headache. I'm sure I can figure it out, but I'm waiting for the right inspiration to come to me 😎

**Comment by braver** [comment]
Looks good on master now.
