### ISSUE TITLE
SCSS mixin parameters are not turning to orange

### ISSUE THREAD

**Issue by suwaishing** [braver/SublimeSass#17]
### **Problem**

My code is still working, but the @mixin part is wierd. Normally, the variables turn to orange but it's not. 
![image](https://user-images.githubusercontent.com/40514878/47762043-874b0280-dced-11e8-9d14-1aba1f2863f5.png)
### **Environment**

- Sublime text version 3.1.1, build 3176
- Sass v2.0.3

**Comment by suwaishing** [comment]
First of all, I highly appreciate your work here with quickly respond.
Secondly, there's still a problem with the @mixin parameter and SCSS parameters, as below
![image](https://user-images.githubusercontent.com/40514878/47827291-6cd95d80-ddaf-11e8-9c23-fcbbe7a75afd.png)

and this is SCSS parameters
![image](https://user-images.githubusercontent.com/40514878/47827323-aa3deb00-ddaf-11e8-9c73-d1d3b54e1536.png)

### **Environment**

- Sublime text version 3.1.1, build 3176
- Sass v2.0.7 (updated)

**Comment by braver** [comment]
What's the problem actually? Variables are white in Monokai (also see #22). The second screenshot doesn't show any parameters?
