### ISSUE TITLE
plugin_host error

### ISSUE THREAD

**Issue by DRYN07** [braver/SublimeSass#18]
Hey guys, I get this error after the update. I tried to reinstall but only remove/disable solve it :/

![error](https://user-images.githubusercontent.com/29770761/47772213-3e438000-dce6-11e8-8996-85cc7c1ad153.jpg)

**Comment by braver** [comment]
@DRYN07 Does the console show any useful information? You may also have some other packages installed that interact with the Sass package in an unexpected way. What packages do you have installed?

**Comment by luisdeprati** [comment]
I solved out updating my sublime version, maybe your problem could be solved the same way.

**Comment by cesc1989** [comment]
> I solved out updating my sublime version, maybe your problem could be solved the same way.

Same here. Updating sublime solved the thing.

**Comment by DRYN07** [comment]
I don't remember I updated or not but my error also dissapeared. Funny :)

Thanks for the suggestions anyway
