### ISSUE TITLE
error: sass syntax @function highlight

### ISSUE THREAD

**Issue by CreativSpeed** [braver/SublimeSass#19]
@function and all @* syntax highlight detected as a string.unquoted.css

![sass-error](https://user-images.githubusercontent.com/12558150/47789675-7910dc80-dd15-11e8-9f09-0f689623deeb.png)

**Comment by braver** [comment]
@CreativSpeed that's probably due to the `@return` statement not ending correctly. Fixed in 201e921ad2fb23ee06b490c58ded44d78558cc07

**Comment by CreativSpeed** [comment]
no, you cant do that in .sass

![sass-error-2](https://user-images.githubusercontent.com/12558150/47796059-dd3a9d00-dd23-11e8-9aaa-6ad4e2c34354.png)
