### ISSUE TITLE
Releasing package on package control

### ISSUE THREAD

**Issue by pratikborsadiya** [braver/SublimeSass#2]
Can you release this package on package control? May be under different name as the original author P233 is not available to transfer the package authority.

**Comment by braver** [comment]
I'm currently trying to reach out to P233. If he doesn't respond this month (no hurry and I'll be on holiday anyway) I'll update the entry in package control to point to this fork. Preferable he responds and is able to cooperate in some way, but one way or another it'll happen soon.

**Comment by pratikborsadiya** [comment]
Thank you so much for reviving the syntax. I will look forward to see this on package control.

**Comment by braver** [comment]
We can track this here now: 
https://github.com/wbond/package_control_channel/pull/7220
