### ISSUE TITLE
Doesn't really feel like New Syntax Highlighting is been working correctly

### ISSUE THREAD

**Issue by Security2431** [braver/SublimeSass#21]
Hey! I have updated sass plugin, but this is what i saw [https://snag.gy/NK6uLv.jpg](https://snag.gy/NK6uLv.jpg). The previous syntax highlighting was much more separated. I use Sublime Text 3.1.1, Build 3176.

**Comment by braver** [comment]
Please check again with 2.0.5. If you want to share some code so I can test it, that'd be useful as well.

**Comment by Security2431** [comment]
Feel free to test this one https://github.com/kvkgroup/domcom/blob/master/app/sass/pages/_main.sass

**Comment by braver** [comment]
Thanks!
