### ISSUE TITLE
SCSS variable highlighting stopped working

### ISSUE THREAD

**Issue by dylanfisher** [braver/SublimeSass#22]
Using `v2.0.7`

Highlighting just disappeared for SCSS variables. Pretty sure this was working prior to `v2.0.7`.

<img width="796" alt="screen shot 2018-10-31 at 4 06 24 pm" src="https://user-images.githubusercontent.com/3743491/47815672-5edffa00-dd27-11e8-9ce6-20064181886a.png">

**Comment by braver** [comment]
That might just be what variables look like in your color scheme. What do variables look like in say JavaScript?

**Comment by dr-dimitru** [comment]
@braver same, here, again:
![screen shot 2018-11-03 at 1 44 50 am](https://user-images.githubusercontent.com/1686778/47945425-9955bc80-df0a-11e8-9b72-12ec44fbcc64.png)
where:
 - `@media` should be red
 - all variables orange and italic
 - `backdrop-filter` should not be red

**Comment by dr-dimitru** [comment]
@braver here is how js code is highlighted
![screen shot 2018-11-03 at 12 14 18 pm](https://user-images.githubusercontent.com/1686778/47950890-0ba5bb80-df62-11e8-91f2-495c2b73e3fd.png)

**Comment by braver** [comment]
- Parameters in a function definition should be orange italic, and they are.
- Variables should be white. When they’re defined and whenever they’re used. Variables passed as parameters to a function call should also be white. 

Your JS example clearly shows that as well:

- In the definition of `sampleFunc` the args are orange
- The `obj` variable is always white
- The `obj` variable is also white when passed as a paramter to `set.add`


The old version of Sass got it wrong, it’s probably the only syntax out there that scopes things like it does.

**Comment by braver** [comment]
> @braver same, here, again:
> ![screen shot 2018-11-03 at 1 44 50 am](https://user-images.githubusercontent.com/1686778/47945425-9955bc80-df0a-11e8-9b72-12ec44fbcc64.png)
> where:
> 
> * `@media` should be red
> * all variables orange and italic
> * `backdrop-filter` should not be red

You may be right about the `@media` and the `backdrop-filter` though.

**Comment by dr-dimitru** [comment]
Not sure if this one deserves separate issue:

```sass
.sidebar
  background: none
  @media(max-width: $break-parent)
    will-change: transform, scroll-position
```

```sass
.sidebar
  background: none
  will-change: transform, scroll-position
```
Where `transform` and `scroll-position` has two different colors
![screen shot 2018-11-14 at 7 54 32 pm](https://user-images.githubusercontent.com/1686778/48502155-8b2b6880-e847-11e8-97ba-53bd61f962a2.png)

**Comment by braver** [comment]
I'm closing this. The original issue as far as there was any has been resolved. `backdrop-filter` isn't a standardized property and therefore not recognized. In any case that's something completely seperate from the original issue. @dr-dimitru this is something else, unrelated to the other issues raised here. I don't have a fix for that yet, but have a test in place and will look at a solution soon.
