### ISSUE TITLE
SCSS parameters and boolean type coloring issue

### ISSUE THREAD

**Issue by suwaishing** [braver/SublimeSass#23]
First of all, I highly appreciate your work here with quickly respond.
Secondly, there're still problems with the parameters and value true false in SCSS, as below
![image](https://user-images.githubusercontent.com/40514878/47827291-6cd95d80-ddaf-11e8-9c23-fcbbe7a75afd.png)

and this is SCSS parameters
![image](https://user-images.githubusercontent.com/40514878/47827323-aa3deb00-ddaf-11e8-9c73-d1d3b54e1536.png)

### **Environment**

- Sublime text version 3.1.1, build 3176
- Sass v2.0.7 (updated)

### **More info**

- The parameter was orange and True/False value was not yellow before. So I think it's nothing to do with color scheme.

- And it's look normal in Javascript:
![image](https://user-images.githubusercontent.com/40514878/47827813-87610600-ddb2-11e8-9afa-61b3939c18fb.png)

_Originally posted by @suwaishing in https://github.com/braver/SublimeSass/issue_comments#issuecomment-434901376_

**Comment by braver** [comment]
Just to make sure I understand you correctly:
- parameters in a function definition should be orange in Monokai, so that's correct
- boolean values aren't recognized and are now incorrectly colored yellow, so that's an actual bug

**Comment by Migshu** [comment]
Variables ceased to be painted in orange color. In addition, the compiler (Koala) does not see them, gives an error. What to do?
![2018-11-02 19 42 12](https://user-images.githubusercontent.com/44707402/47928492-97bed100-ded7-11e8-941f-6a70bffb7c21.png)
![2018-11-02_19-45-31](https://user-images.githubusercontent.com/44707402/47928661-e9675b80-ded7-11e8-9748-2f710f53aaca.png)
![2018-11-02_19-46-50](https://user-images.githubusercontent.com/44707402/47928731-1156bf00-ded8-11e8-9ea8-26332a32f07a.png)

**Comment by Migshu** [comment]
> The old version of this package used incorrect scopes for variables.

Thanks for your prompt reply!

**Comment by braver** [comment]
Closed: variables shouldn't be orange, true/false constants have been added in 2.2.1
