### ISSUE TITLE
Multiple regressions and suggestions after update

### ISSUE THREAD

**Issue by sandrojohanides** [braver/SublimeSass#24]
Hey there, thanks for the update. I have found multiple regressions I think (would have to compare with previous version). Also some of these may be suggestions, because I’m not sure if they are broken or not. If there’s any more information I can give you, let me know :)

A before/after would be best I guess, is there a way to install a specific version of a package?

### 1.
![screen shot 2018-11-01 at 09 38 44](https://user-images.githubusercontent.com/8327913/47841831-30136380-ddbb-11e8-9dce-35b256467b18.png)
- `@ $ .` all have the same color, some of it I don’t mind, but `$` not having the variable colors seems wrong
- `header, aside, main` look like strings, even without 'quotes'
- `@supports` is a css thing, but `@each` is from Sass, not sure if they should look the same

### 2.
![screen shot 2018-11-01 at 09 39 07](https://user-images.githubusercontent.com/8327913/47841832-30136380-ddbb-11e8-9cd7-8f43b5e231e5.png)
- `minmax(auto, max-content)` has variable highlighting, but both are native keywords for the minmax function

### 3.
![screen shot 2018-11-01 at 09 40 08](https://user-images.githubusercontent.com/8327913/47841833-30136380-ddbb-11e8-913e-2c9d0a806fd5.png)
- `color(dark-grey)` loses highlight color after the dash
- but `font-size(tiny)` has different whole different color (looks like a string)

### 4.
![screen shot 2018-11-01 at 09 40 26](https://user-images.githubusercontent.com/8327913/47841834-30abfa00-ddbb-11e8-8048-f74aef10b9cb.png)
- `color(darker)` have the same color, but `color(white)` look different, because white is a keyword (but the `darker` color is incorrect)

### 5.
![screen shot 2018-11-01 at 09 41 03](https://user-images.githubusercontent.com/8327913/47841835-30abfa00-ddbb-11e8-9bb5-fbf921e4ef38.png)
- `width: fit-content` highlight looks like a string, but is a keyword (see `auto`)

### 6.
![screen shot 2018-11-01 at 09 41 42](https://user-images.githubusercontent.com/8327913/47841837-30abfa00-ddbb-11e8-9e14-9e2cd80b7fe1.png)
- `reveal-right` is the animation name
- `time(normal)` is a custom function, normal is a keyword so it has its own color
- `bezier(nudge)` is a custom function with a string as an argument
- `forwards` is a keyword
- point is they work kinda correct, but look too random, i think before the keywords and custom strings had the same color, so the rule had less color highlighting

### 7.
![screen shot 2018-11-01 at 09 42 02](https://user-images.githubusercontent.com/8327913/47841838-30abfa00-ddbb-11e8-801d-b74903eb2b29.png)
- different color of the same custom function `rem()`

### 8.
![screen shot 2018-11-01 at 09 45 03](https://user-images.githubusercontent.com/8327913/47841839-30abfa00-ddbb-11e8-8c0f-cacb474114a5.png)
- @mixin parameter `scope` has different color than a variable
- `ie9` string after `==` has two colors, one for text, one for number
- `:root` is a selector, but looks like a variable

### 9.
![screen shot 2018-11-01 at 09 46 23](https://user-images.githubusercontent.com/8327913/47841840-31449080-ddbb-11e8-9594-eacabc1a8cf7.png)
- seemingly random highlighting of these rules and thier values

### 10.
![screen shot 2018-11-01 at 09 47 08](https://user-images.githubusercontent.com/8327913/47841841-31449080-ddbb-11e8-8b7c-7cd154cf56ac.png)
- custom `em()` function looks differently in maps

**Comment by sandrojohanides** [comment]
I installed the previous (1.) version to compare, so if you need before/after, let me know.

**Comment by braver** [comment]
Wow, lot's of feedback, thanks! I'll try to address them one by one:

>@ $ . all have the same color, some of it I don’t mind, but $ not having the variable colors seems wrong

That's up to the color scheme what happens with the colors. But it's actually common and recommended to scope the punctuation differently: https://www.sublimetext.com/docs/3/scope_naming.html#keyword
E.g. the `--` in a `--custom-property` is also different.

> header, aside, main look like strings, even without 'quotes'

In this context, they're actually (unquoted) strings. Only when they are used is the string interpreted as (part of) a selector in your example, but they could just as well be values for a property, or a property name. Strings don't always need quotes in CSS and unquoted strings are similarly colored to quoted strings.

> @supports is a css thing, but @each is from Sass, not sure if they should look the same

They are differentiated in the scope (it ends with either `sass/scss` or `css`), so you could actually tweak your color scheme to give them a different color. Remember, a syntax is about identifying and labelling the different parts of your code, not about giving them a particular color.

> minmax(auto, max-content) has variable highlighting, but both are native keywords for the minmax function

I think I need to look at the grid features in more detail to get this right. Thanks!

> color(dark-grey) loses highlight color after the dash
> but font-size(tiny) has different whole different color (looks like a string)
> color(darker) have the same color, but color(white) look different, because white is a keyword (but the darker color is incorrect)
> width: fit-content highlight looks like a string, but is a keyword
> different color of the same custom function rem()

Good catches, some look really like legit bugs, will look into it!

> point is they work kinda correct, but look too random

That does look a bit random, I'll see what makes sense here. Not all color schemes are as "wild" with their colors though, so this will be different for everyone.

> @mixin parameter scope has different color than a variable

Yes, that's correct, parameters are different. 

> ie9 string after == has two colors, one for text, one for number

Hey, that's not right! 👍 

> :root is a selector, but looks like a variable

Nothing I can do there I'm afraid. I scoped it correctly, so the color scheme just makes it more confusing.
<img width="251" alt="screen shot 2018-11-01 at 14 07 38" src="https://user-images.githubusercontent.com/2543659/47853611-8e523d80-dddf-11e8-94d9-ead7aee5ebed.png">

> seemingly random highlighting of these rules and thier values

Ugh, those pesky vendor prefixes!

> custom em() function looks differently in maps

Thanks for catching that!

**Comment by braver** [comment]
TODO: 

- [ ] grid minmax function
- [ ] color(dark-grey) loses highlight color after the dash
- [ ] but font-size(tiny) has different whole different color (looks like a string)
- [ ] color(darker) have the same color, but color(white) look different, because white is a keyword (but the darker color is incorrect)
- [ ] width: fit-content highlight looks like a string, but is a keyword
- [ ] different color of the same custom function rem()
- [ ] seemingly random highlighting of these rules and thier values
- [ ] ie9 string after == has two colors, one for text, one for number
- [ ] custom em() function looks differently in maps

**Comment by cyril-lamotte** [comment]
![2018-11-05 09_18_23-d__www-drupal_mmh_src_src_mmh-corporate_docroot_themes_custom_mmh_sources_scss_c](https://user-images.githubusercontent.com/1423805/47986036-c9a08500-e0db-11e8-854f-c14ac4a642ee.png)

Hi, thanks for your work, I figure that inline comment has been altered too ?

**Comment by braver** [comment]
@sandrojohanides this is already very useful for me. I can take these examples to set up a test case and then make it pass the test. Having raw code in addition to the screenshot would be nice though.

**Comment by sandrojohanides** [comment]
@braver https://gist.github.com/sandrojohanides/6fc15dacad3b612584a493f1b26030bc
^ Here they are, if you want to see how they looked like 'before', save it as .scss and look at it with the P233 version, but I don’t have to tell you that. Also, I copied all of the cases, even the non-bug ones, you’ll know which to use.

I’m currently still using the old version, but will test yours when you put out a new release.

**Comment by braver** [comment]
A new release is out that should fix the issues with import statements. Thanks for testing and reporting everyone!

**Comment by braver** [comment]
![](https://user-images.githubusercontent.com/8327913/48001996-83aee580-e10a-11e8-9b9b-dfab30496b6e.png)

👆 this one is also fixed now!

**Comment by sandrojohanides** [comment]
@braver `@import`s seem to work great! But no all comments are fixed, there’s still the case with a comment after a comma (updated previous comment and gist).

**Comment by sandrojohanides** [comment]
### 9.
![screen shot 2018-11-06 at 09 35 49](https://user-images.githubusercontent.com/8327913/48052327-e904e400-e1a7-11e8-84df-1c2b455c7ff0.png)
![screen shot 2018-11-06 at 09 36 04](https://user-images.githubusercontent.com/8327913/48052328-e99d7a80-e1a7-11e8-9b20-876988297de5.png)

- interesting case with the pesky vendor prefixes, the difference between a single and a double colon `: ::`

**Comment by treechime** [comment]
I've noticed a couple of things too...

1. Coloured bracket on nested element with ampersand in selector (it might be difficult to see with my theme, but it's purple when it should be white)
1. No space after colon causes incorrect url highlighting (I prefer not adding spaces as the rivers this creates in the code makes it difficult to read imo)

![image](https://user-images.githubusercontent.com/8661599/48330578-b3289980-e698-11e8-95fd-6534fdcdfd74.png)

**Comment by braver** [comment]
FIY a little update here. The primary trick of both LESS and SCSS is differentiating between properties and selectors, especially when dealing with pseudo selectors (they make them look like properties). I thought I found a shortcut that would still make them stick very closely to the CSS syntax. Sadly, that breaks in various less obvious ways. 
So, I’m currently rewriting this to be rock solid, no shortcuts. It’ll be next level 💪🏻😎. But it probably also means I need to recreate small things like auto-complete as well, so it’s not ready yet.

**Comment by sandrojohanides** [comment]
@braver thank you for your work 🔥

**Comment by cyril-lamotte** [comment]
Hi,

I got this today :

![2018-11-15 09_45_17-d__www-drupal_cridf_src_src_portailidf-d8_projet_web_themes_custom_portail_idf_s](https://user-images.githubusercontent.com/1423805/48540751-417c6580-e8bb-11e8-93ca-6be7f0cfd8d0.png)

**Comment by braver** [comment]
Alright, status update. I got it working as I hoped it would for LESS. Will be porting that to SCSS, which should be easy (SCSS is a *much* easier language to work with), so expect more news and maybe even a release in the coming days.

**Comment by braver** [comment]
Hey all, if you're using the SCSS syntax you may want to check master. I want to do some more tests and I need to check the autocompletion stuff etc., but it should be *a lot* more robust. Going through some test files it already looks a lot better. Let me know what you think!

**Comment by taunoha** [comment]
@braver thank you for the update! I tested the new SCSS syntax and got this:

_Before:_
![screenshot 2018-11-06 16 23 57](https://user-images.githubusercontent.com/7137679/48920218-3ff50380-eea0-11e8-8468-f41d59eb63ec.png)

_After:_
![screenshot 2018-11-06 16 20 59](https://user-images.githubusercontent.com/7137679/48920238-5ac77800-eea0-11e8-8a17-7733ee33165e.png)

_After using current SCSS syntax in Master:_
![screenshot 2018-11-22 21 44 57](https://user-images.githubusercontent.com/7137679/48920185-1b009080-eea0-11e8-9342-411af89b4683.png)

**Comment by braver** [comment]
@taunoha can you share the code so that I can copy-paste to recreate those snippets?

**Comment by taunoha** [comment]
> @taunoha can you share the code so that I can copy-paste to recreate those snippets?

Here it is:
`@each $icon in $icons-16 {
    %icon-#{$icon}--primary {
        background-image: svg('icon__#{$icon}-16', '[fill]: #{theme-color("primary")}');
    }
}

@each $icon in $icons-16 {
    %icon-#{$icon}--muted {
        background-image: svg('icon__#{$icon}-16', '[fill]: #{$text-muted}');
    }
}`

https://codeshare.io/amm0rj

**Comment by braver** [comment]
@taunoha I think master now covers those cases as well. It won't match the old highlighting, but it should be correct.

**Comment by sandrojohanides** [comment]
Hey @braver,
1. When I install this package by adding this repository into Sublime Text, does it install the code from `master`?
2. When do you want me to send you new or persisting usecases? I don’t know if you’re done with this batch yet.

Thank you!

**Comment by braver** [comment]
2.2 should cover most of what has been mentioned here. If there are problems remaining, please open a new issue.
