### ISSUE TITLE
Go to Feature not working (v2.1.3)

### ISSUE THREAD

**Issue by AndresPF** [braver/SublimeSass#32]
I use go to definition and symbol a lot.

After one of the updates I haven't been able to use these feature correctly. (can't really tell which update specifically because I don't usually turn off my computer or close sublime in general.)

Go to Symbol
![screen shot 2018-11-14 at 9 17 19 am](https://user-images.githubusercontent.com/8027791/48492153-c2b9f680-e7ee-11e8-9da5-546996651396.png)

Go to definition
Here I would normally be able to navigate to the file that has the mixin but now it won't event try
![screen shot 2018-11-14 at 9 20 30 am](https://user-images.githubusercontent.com/8027791/48492201-de250180-e7ee-11e8-9822-f315cc04a4cf.png)

Go to symbol sort of works if I change the `@` to a `#`
![screen shot 2018-11-14 at 9 23 48 am](https://user-images.githubusercontent.com/8027791/48492285-11679080-e7ef-11e8-948e-f17d5bb5377c.png)

I haven't done any modifications to any file. 😢

**Comment by Gargron** [comment]
Same. This seriously interferes with my workflow :(

**Comment by braver** [comment]
2.2.2 restores goto definition for mixins. Let me know if that makes it work again for you!

**Comment by AndresPF** [comment]
Goto mixins work but it still won't recognize IDs or classes 😢

**Comment by braver** [comment]
@And

**Comment by braver** [comment]
@AndresPF Right now it works exactly as it does in other programming languages (ie. list function definitions etc). 
But unlike CSS it doesn't list all selectors... because selectors can be nested so including them in the symbol list needs some extra care. I think that's what you're missing here right? The selectors in the `@` list?

**Comment by AndresPF** [comment]
@braver sorry for late response!

Yes that is exactly what I'm missing. It used to work just fine but I guess probably nested selectors would be difficult to implement. 

Thanks! I'm so happy with Go to definition working.

**Comment by braver** [comment]
Glad you're happy with it. By the way, I forgot to update earlier, but the listing of all selectors is back too. Wasn't even that hard once I figured it out.
