### ISSUE TITLE
Grid values

### ISSUE THREAD

**Issue by sandrojohanides** [braver/SublimeSass#49]
There are various little bugs in grid values (keywords, numbers, etc.). The syntax sections of these can be used to create tests:

https://developer.mozilla.org/en-US/docs/Web/CSS/grid
https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns
https://developer.mozilla.org/en-US/docs/Web/CSS/grid-auto-columns

Let me know if you want me to point out the specifics.

**Comment by braver** [comment]
Thanks! The MDN docs are super valuable, I think I'll manage with those links.

**Comment by braver** [comment]
@sandrojohanides I pushed some fixes for grid syntax. Anything in particular that's still broken or missing for you?

**Comment by sandrojohanides** [comment]
Look beautiful, only bug I see is with the `auto-fit` and `auto-fill` keywords, which should be red.
![screen shot 2018-12-07 at 17 57 17](https://user-images.githubusercontent.com/8327913/49661559-a6a22180-fa49-11e8-9d24-3b9aeb637d58.png)

From here: https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns

**Comment by braver** [comment]
Just like in the CSS syntax, they're labelled as `support.keyword.repetitions.css`. I don't know why exactly. I value the consistency with the CSS, so if you want this changed better open an issue there. 

I'm going to  close this issue, if you find anything else, please report! Thanks so much for cooperating this last week! 🏅
