### ISSUE TITLE
Incorrect highlighting for negation pseudo-class

### ISSUE THREAD

**Issue by indrekpaas** [braver/SublimeSass#5]
IIRC this issue was introduced with the most recent updates.

![image](https://user-images.githubusercontent.com/6239035/45464976-65ee8100-b756-11e8-8915-362ba229fd9b.png)
![image](https://user-images.githubusercontent.com/6239035/45464982-6b4bcb80-b756-11e8-8611-10d527803cc3.png)

**Comment by braver** [comment]
Thanks!
