### ISSUE TITLE
Interpolating functions with parameters

### ISSUE THREAD

**Issue by IIFLIPII** [braver/SublimeSass#51]
The following breaks, whenever an interpolated function is called with a parameter like this:

![bildschirmfoto 2018-12-04 um 10 03 21](https://user-images.githubusercontent.com/38748359/49430654-e21fc000-f7ab-11e8-9b9a-27a2b23d7f57.png)

Remove the parameter and it works fine:

![bildschirmfoto 2018-12-04 um 10 09 18](https://user-images.githubusercontent.com/38748359/49430989-afc29280-f7ac-11e8-87c0-fdae1830c6ff.png)

Some other test cases where only the last one starting with unquoted letters breaks:

![bildschirmfoto 2018-12-04 um 10 08 54](https://user-images.githubusercontent.com/38748359/49430970-a20d0d00-f7ac-11e8-90cf-2a8a83734cb1.png)

Here's the code for testing purposes if needed:

```
$variable: '#{$font-path}#{get-font-name()}/dt_primary_#{$size}';
$variable: '#{$font-path}#{get-font-name("param")}/dt_primary_#{$size}';
$variable: '#{$font-path}#{get-font-name(param)}/dt_primary_#{$size}';
$variable: '#{$font-path}#{get-font-name(12param)}/dt_primary_#{$size}';
$variable: '#{$font-path}#{get-font-name(param12)}/dt_primary_#{$size}';
```

**Comment by braver** [comment]
Thanks!
