### ISSUE TITLE
Couldn't find new package easily

### ISSUE THREAD

**Issue by lukehatfield** [braver/SublimeSass#55]
Would it be a good idea to add a note in the readme that this package as been moved to "Syntax Highlighting for SASS"? I downloaded that package in Sublime Text and I think it is the most current version?

**Comment by braver** [comment]
❓

The old version of the Sass package is now listed as “Syntax Highlighting for Sass”. The README says so. The current version is in the repo you’re looking at here. If you had the Sass package installed it will have been updated correctly already, no need to switch over or anything.
