### ISSUE TITLE
Colon snippet conflicts with vintage mode command palette (i.e. save)

### ISSUE THREAD

**Issue by heimer16** [braver/SublimeSass#59]
depending on the position of the cursor, pressing the colon inserts the :; snippet instead of bringing up the command palette (like doing :w to save).

I tried copying the key binding to my config and add an exclusion for command mode context, but that didn't seem to work:

`{ "key": "setting.command_mode", "operator": "equal", "operand": false },`

my current solution is to override by including the default vintage key binding in my config:

`    { "keys": [":"], "command": "show_overlay", "args": {"overlay": "command_palette", "text": ":"},
		"context": [{"key": "setting.command_mode"}]
	},
`

**Comment by braver** [comment]
Yeah, I guess that workaround is what you need to do. I don't like shipping key bindings with packages exactly because of this reason. However, it's there because it has been for ages and removing it will change the behavior for all users. I don't know a good solution here.

**Comment by braver** [comment]
I'm considering removing the keybinding for the release of this package that will coincide with general release of ST4. That seems as good a time as any to break stuff. And everyone who needs it can of course always bring it back.
