### ISSUE TITLE
Incorrect highlighting for attribute and pseudo-class compound selectors

### ISSUE THREAD

**Issue by indrekpaas** [braver/SublimeSass#6]
![image](https://user-images.githubusercontent.com/6239035/45658671-c2c1b100-bb33-11e8-86ed-d196948dd894.png)
![image](https://user-images.githubusercontent.com/6239035/45658678-c7866500-bb33-11e8-8892-03d5da733294.png)

**Comment by braver** [comment]
Thanks!
