### ISSUE TITLE
No autocompletion of values in SASS and SCSS

### ISSUE THREAD

**Issue by MaxiNCh** [braver/SublimeSass#68]
I installed SASS package it works well. But autocompletion of values doesn't work in .scss and .sass files.
In description it's written that there should be autocopletion. Maybe SASS interfere with other packages? I have several:
- Emmet
- HTML/CSS/JS Prettifier
- A file Icon
- Bracket HIghlighther

**Comment by braver** [comment]
Emmet is probably the package that breaks this. Please try it without Emmet.

**Comment by MaxiNCh** [comment]
> Emmet is probably the package that breaks this. Please try it without Emmet.

I disabled Emmet, but still no autocompletion of values in .sass and .scss. 
In .css it works well.. strange.

**Comment by braver** [comment]
Well, it works on my end and not on yours, so that makes it pretty hard for me to help you out without more information. Disable all other packages and check the console for information?

**Comment by MaxiNCh** [comment]
> Well, it works on my end and not on yours, so that makes it pretty hard for me to help you out without more information. Disable all other packages and check the console for information?

I disabled packages. Sometime autocompleteion works. But if I restart my computer it doesn't work again.
Then I try to work with different files .css, .sass, .scss and it again works. But I cannot catch and cannot understand what do I do when it starts work.
My console:
[console.txt](https://github.com/braver/SublimeSass/files/5204245/console.txt)

**Comment by MaxiNCh** [comment]
> And if you try to trigger an autocompletion, do any errors show up in the console?

No. 
Instead of autocompletion of values ST suggest autocompletion of words from current file.
But still sometimes it starts to work until I restart ST or restart computer

**Comment by braver** [comment]
Well, shit. That also means I can't help you.

**Comment by MaxiNCh** [comment]
Hmm.. I've just noticed that if I close ST with opened .sass file - when I start ST autocompletion doesn't work.
When I close ST when opened only .scss file - when I  ST autocompletion works..
Very strange for me..

**Comment by MaxiNCh** [comment]
Hope, I'll find the reason.. Thank you for support and for the plugin anyway!

**Comment by borodean** [comment]
The current version of the plugin uses the ST4 API that is not available for mere mortals yet. For example, accessing attributes like `sublime.KIND_ID_KEYWORD` and `sublime.KIND_ID_FUNCTION` completely break `sass_completions.py` execution.

cc @braver

**Comment by braver** [comment]
Oh, crap, I was afraid that an ST4 feature would slip in. I probably need to simply roll back to an earlier release.

**Comment by braver** [comment]
Well that was amateurish and embarrassing 🤦🏼‍♂️ Fixed releases are under way for ST3, and new releases are coming for ST4.
