### ISSUE TITLE
Support for CSS Modules

### ISSUE THREAD

**Issue by tuzemec** [braver/SublimeSass#74]
Any plans for supporting [CSS modules](https://github.com/css-modules/css-modules)?

It will be quite nice if there's proper syntax definition for `composes:`, `:global`, `:export` and so on.

**Comment by braver** [comment]
No, there are no plans. Sass has a module system now, and we support that. CSS modules feels kinda like a dead project, and I can't find a very formal spec of the syntax. One problem I see with it is that is introduces property names that are not properties, e.g. `composes`. Anyway, it looks easy enough to implement, but I'd like to know if that is actually a live project that more than a handful of people are using.

**Comment by tuzemec** [comment]
It's just my take on this, but as I see it the css modules are quite popular in the React toolchain. 
The last few projects that I've worked on had some kind of importing SCSS into React components.
Using `composes` is quite rare with SCSS, but things like `:global` and `:export` come handy in a lot some situations.
And again, that's just my take on this and I can be wrong :) 
... or it's just my OCD kicking in when I see something not coloured properly in Sublime :)

**Comment by braver** [comment]
The group around the toolchain does look very active. I can imagine that the syntax is "done" and doesn't need a lot of working on. 
And implementing it wasn't too hard either. Have a look at #75 , see if I missed anything.

**Comment by tuzemec** [comment]
Looks good to me!
