### ISSUE TITLE
[ST4] Upgrade from ST3 required reinstall of this package

### ISSUE THREAD

**Issue by rootwork** [braver/SublimeSass#79]
With ST4 officially out, I tried setting SCCS syntax on a couple of files, and it wasn't coming up as an option in my list of syntax(es).

I uninstalled the package and reinstalled using Package Manager -- the version I had installed was 2.5.0, and on reinstallation it was still 2.5.0.

Unfortunately I'm not sure I can replicate this process to see why it wasn't initially working. I had quit and restarted ST after the upgrade and before I tried using this package, so I know it wasn't that. And other packages I had did make the upgrade in working order. But I thought I'd report it in case you wanted to investigate the upgrade path.

Thanks for maintaining this!

**Comment by braver** [comment]
Hm, I'm afraid that upgrade path is a bit out of my hands. I think what happens is that the st3 version is registered as incompatible with st4 and package control therefore unloads it... not sure if it does that actually. Anyway, when you restart st4, it should pick up the latest st4 version of this package and all is good again. It should be "self healing" in that way, and I wonder why that didn't happen for you. Although I would not be surprised if it took 1 restart to go from 3 to 4, then another restart to upgrade all packages, and then a third one to properly reload all packages and dependencies.

I'll keep an eye out for similar reports, there are more packages out there with separate st3 and st4 releases like this one.
