### ISSUE TITLE
ST4 align-items, align-self ... not reconized as a properties

### ISSUE THREAD

**Issue by artik** [braver/SublimeSass#80]
`align-items` or `align-self` properties is not reconized as a property, when `justify-content` is. Demo:

https://i.imgur.com/klCldih.gif

**Comment by braver** [comment]
And what happens if you add the `:` after `align-items`? Because SCSS is nested, it needs a little help to find out that you're typing a property and not a selector.

**Comment by jfcherng** [comment]
![image](https://user-images.githubusercontent.com/6594915/120489200-08a92b00-c3ea-11eb-82a6-2d3e864952ef.png)

**Comment by artik** [comment]
@braver Yes, it then appears as a property when i add `:`, but `.css` files aren't affected by this behavior:

https://i.imgur.com/h5Bo0ct.gif

And works, adding automatically the `: ;`

**Comment by jfcherng** [comment]
https://github.com/braver/SublimeSass/blob/4ee59a5be9257d5b220c1448000321fc6babd672/Syntaxes/Sass.sublime-syntax#L383

```diff
-     - match: '\s*({{custom_elements}})(?![-:])'
+     - match: '\s*({{custom_elements}})(?!-|\s*:)'
```

**Comment by artik** [comment]
Fixed! thanks @jfcherng

**Comment by braver** [comment]
Good catch @jfcherng implemented your suggested fix.

**Comment by artik** [comment]
Re-opening the issue, I'm affected by the same bug once again. Using `ST4` and Sass.sublime-package` v2.5.3`.
In my package file, the fix is here:

![screenshot01](https://user-images.githubusercontent.com/1015856/130605914-e898087a-a898-4652-94c6-c6b5ec53c6f6.png)

![Peek 2021-08-24 13-02](https://user-images.githubusercontent.com/1015856/130605702-c5ad975d-7dc1-44f0-ac2f-bcb6a2aa9f57.gif)

**Comment by jfcherng** [comment]
Well, you can use `align-items` as a custom tag in HTML5. If you add `:`, then that's what you want.

My another finding is 
![Snipaste_2021-08-24_19-11-38](https://user-images.githubusercontent.com/6594915/130606870-2930651e-f2ee-4e72-baa8-566810f16ec4.png)
I would say this is wrong.

**Comment by artik** [comment]
I have another detail on this bug, it affects some scss files, not all:

![Peek 2021-08-24 13-20](https://user-images.githubusercontent.com/1015856/130607993-4d40e22f-0c16-464b-b4cf-4b9ad97662a1.gif)

**Comment by jfcherng** [comment]
> I have another detail on this bug, it affects some scss files, not all:

I believe I've answered that.
> Well, LGTM. It think you can use align-items as a custom tag in HTML5. If you add :, then that's what you want.

**Comment by artik** [comment]
> > I have another detail on this bug, it affects some scss files, not all:
> 
> I believe I've answered that.
> 
> > Well, LGTM. It think you can use align-items as a custom tag in HTML5. If you add :, then that's what you want.

Understood, but it doesn't tell me why in one file it's properly displayed, not in the other

**Comment by jfcherng** [comment]
> Understood, but it doesn't tell me why in one file it's properly displayed, not in the other. I'm having 2 different behaviors that mix me a bit when fast coding, really would love to know why and fix it to have the same behavior everywhere.

I was just to answer that the your new question about autocompletion is not relevant to the original one. So re-open this issue is doubtful to me.

**Comment by artik** [comment]
Found something useful. When I write it in one line, it works:

![Peek 2021-08-24 13-40](https://user-images.githubusercontent.com/1015856/130610189-7ad23c88-9d45-44a1-babe-0267b0f04606.gif)

**Comment by jfcherng** [comment]
There are probably 3 kinds of autocompletion involved in.

1. The one without kind info provided. Probably comes from ST's word completion or outdated plugin.

![Snipaste_2021-08-24_19-40-39](https://user-images.githubusercontent.com/6594915/130610280-e38625f4-0059-411c-919e-83b3d7a3c173.png)

2. The one with kind info provided (i.e., the prefixed pink `p`). Probably comes from ST's symbol index or modern plugin like LSP-css.

![Snipaste_2021-08-24_19-42-32](https://user-images.githubusercontent.com/6594915/130610441-2cc16b7b-c18b-4183-b2d9-5cd16fbacce6.png)

3. The green background one, which comes from Emmet.

![Snipaste_2021-08-24_19-46-48](https://user-images.githubusercontent.com/6594915/130610965-08739f40-143f-400e-ba32-e25e3d10dd1f.png)

---

But I don't know what's going on here and don't know how to fix it.

**Comment by artik** [comment]
All clearer, thanks. I'll try to deactivate plugins and investigate. If I can't find I'll post on ST forums.

**Comment by artik** [comment]
Interesting answer from Deathaxe https://forum.sublimetext.com/t/bug-st4-auto-completion-doesnt-work-properly-in-scss-files/60386/8?u=artik

```
This issue is a package issue only for sure.

Sass package provides its own sass_completions.py plugin which provides those completions.

The default css_completions.py which ships with ST’s CSS syntax package, does not handle SCSS at all. It just returns “I have nothing to add here”. So this one is not to blame.

ST correctly calls on_query_completions in both illustrated situations. So it’s not a core issue either.

It’s SASS’s sass_completions.py which returns nothing in your second example, because as soon as you type a character, it is scoped meta.selector, which causes the completions plugin to return None at line 644 as it doesn’t handle them.
```
braver/SublimeSass/blob/d3d94046409db6fbbc9d51dea52b589ecc9d3d48/sass_completions.py#L632-L633

**Comment by braver** [comment]
Probably it's that without further information the syntax cannot decide if `align-items` is a custom selector or a property key, and therefore cannot provide you with suggestions. I'm not 100% sure it can be solved completely, but let's keep this open and see what happens.

**Comment by artik** [comment]
But the fact that in one line it works, I don't understand why when it's intended it doesn't, and shouldn't be different : https://github.com/braver/SublimeSass/issues/80#issuecomment-904563611

I also think most devs would prefer by default a property completion (and removing the `:` if they want a selector). Quite tricky to name a selector `align-items`.

If this cannot be commited in the git, maybe you can tell me wich part to the `sass_completions.py` I can change to force the completion? It would be amazing as this property drives me crazy everytimes I use it during the day :)

**Comment by braver** [comment]
A 3.0 beta release is out now, check [the readme](https://github.com/braver/SublimeSass#30-beta-release) on how to get the early builds to take advantage of the improvements and help out improving the package before we ship it to the world.

**Comment by artik** [comment]
Woaw, looks fixed in beta! Back to fast coding again, thanks for your work. I'll try it deeper in the coming days. I switch this one to `close`, and re-open a new issue if I find one.
