### ISSUE TITLE
CSS logical properties syntax highlghting

### ISSUE THREAD

**Issue by dwhenson** [braver/SublimeSass#85]
Hi, just to mention that some of the newer css properties don't seem to be recognised by the Sass package. I'm thinking logical properties and some of the recent grid properties (e.g. place-items.) I've attached an image showing the issue. If you need more details just let me know.
Thanks
<img width="491" alt="Screenshot 2021-08-12 at 19 38 05" src="https://user-images.githubusercontent.com/50716370/129236951-2beaf6a8-9aa3-4e86-9de6-adf32e74861c.png">

**Comment by braver** [comment]
The first question is always: are they supported by the default CSS package?

**Comment by dwhenson** [comment]
Yes, if I switch the syntax to css it seems fine. See attached screenshot. 
<img width="491" alt="Screenshot 2021-08-13 at 15 26 46" src="https://user-images.githubusercontent.com/50716370/129356850-de3f2b3c-236c-4797-a66b-da8dcf71d706.png">

**Comment by braver** [comment]
Thanks for checking that. I’m busy “re-basing” this package on the default CSS syntax, which is quite a bit of a project, so this should resolve itself when that gets done.

**Comment by dwhenson** [comment]
Brilliant - thanks so much. Appreciate the hard work!!

**Comment by dwhenson** [comment]
Hey. Just checking in how the work is going? I'm sure it's a lot but super excited to try this out!

**Comment by braver** [comment]
I’ve been use-testing it for a while now me and it seems fine I guess. Haven’t run into anything big really. I want to have closer look at the completions before I tag a release though.

**Comment by dwhenson** [comment]
Hello me again.... just checking in to see if you are planning a release anytime? Is there a way I can try and then let you know if I encounter any issues, or help in any other way?

**Comment by braver** [comment]
A 3.0 beta release is out now, check [the readme](https://github.com/braver/SublimeSass#30-beta-release) on how to get the early builds to take advantage of the improvements and help out improving the package before we ship it to the world.

**Comment by dwhenson** [comment]
Looks beautiful! Great stuff. I'll keep an eye out and let you know if I see any issues...Lovely!!
