### ISSUE TITLE
Beta 3.0: Double entry on listing 

### ISSUE THREAD

**Issue by artik** [braver/SublimeSass#88]
Hard to reproduce, but I had 2x entries in completion menu using 3.0 beta package:

![screenshot02](https://user-images.githubusercontent.com/1015856/150148228-a7e588ba-e36a-4046-8db0-0bf7b4b4b16b.png)

Maybe because I was writing css directly in a `.tpl`, not in a `.scss` file

**Comment by braver** [comment]
Thanks, I think I fixed this (release/tag coming later today).
