### ISSUE TITLE
Beta 3.0: aspect-ratio property doesn't have auto-complete

### ISSUE THREAD

**Issue by artik** [braver/SublimeSass#91]
The `aspect-ratio` property (https://developer.mozilla.org/fr/docs/Web/CSS/aspect-ratio) doesn't have auto-complete:

![Peek 2022-01-21 17-18](https://user-images.githubusercontent.com/1015856/150562053-fc18b5ae-a48e-47b6-be8b-825c926b4b2b.gif)

**Comment by braver** [comment]
I don't believe the default CSS package provides this either, and I follow that implementation. So if you want support for this, the best way to go is to start [there](https://github.com/sublimehq/Packages).

**Comment by artik** [comment]
Great, thanks
