### ISSUE TITLE
3.0.0-beta2: box-shadow, background-* auto-completion is broken

### ISSUE THREAD

**Issue by artik** [braver/SublimeSass#92]
`Box-shadow`,  `background-*` auto-completion is broken (again?). I don't remember having these issues with 3.0.0 beta1. You can also see that they don't have the `P` of property in their name anymore. 

![Peek 2022-01-24 21-08](https://user-images.githubusercontent.com/1015856/150856693-a67d85d5-4f23-4561-9ede-58c88be9ad85.gif)

Confirmed, here is properties listing on `beta1`:

![screenshot06](https://user-images.githubusercontent.com/1015856/150857623-cf1ac451-e90d-42a6-a2c6-eccf7b323bef.png)

**Comment by braver** [comment]
Should be fixed in 3.0.0-beta.3 although I'm not sure what's causing it (looks like a bug in ST?)
